<?php

// autoload.php @generated by Composer
if (PHP_VERSION_ID < 50600) {
    echo 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    exit(1);
}
require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit23c24ed71b72b733931b7c89bd813741::getLoader();
// return ComposerAutoloaderInit451383ba6f81e4b460d2ded5aa0159e1::getLoader();
